devil: Fix installed-vs-shipped error when multilib is disbled
Issue: LINUXEXEC-13268

Fixed when multilib is disabled:
$ bitbake devil
ERROR: devil-1.8.0-r1 do_package: QA Issue: devil: Files/directories were installed but not shipped in any package:
  /usr/lib64/libILU.so.1
  /usr/lib64/libIL.so.1
  /usr/lib64/libIL.so
  /usr/lib64/libILU.so
  /usr/lib64/pkgconfig
  /usr/lib64/pkgconfig/IL.pc
  /usr/lib64/pkgconfig/ILU.pc

Use CMAKE_INSTALL_LIBDIR to replace of lib64 to fix the error.

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>