ti-j72xx: fix missing packages in linux-firmware
Issue: LINCD-4417

This patch fixes the error as below:

ERROR: linux-firmware-1_20201218-r0 do_package: QA Issue: linux-firmware: Files/directories were installed but not shipped in any package:
/lib/firmware/dpaa2/mc/mc_10.18.0_ls2088a.itb
/lib/firmware/dpaa2/mc/mc_10.18.0_lx2160a.itb
/lib/firmware/microchip/mscc_vsc8574_revb_int8051_29e8.bin
....
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
linux-firmware: 2621 installed and not shipped files. [installed-vs-shipped]
ERROR: linux-firmware-1_20201218-r0 do_package: Fatal QA errors found, failing task.

This is because "PACKAGES_ti-j72xx =+" will override PACKAGE variable and make it only to be
"${PN}-cadence ${PN}-cadence-license", and this will trigger do_package_qa failure as above.
So use "PACKAGES_append_ti-j72xx =" to add "${PN}-cadence ${PN}-cadence-license" to the end
of the packages list.

In addition to that, add some LICENSE variables according to the implementation of the package
linux-firmware-imx-sdma-imx7d.

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>